name: samples
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  firebase_analytics: ^10.0.3
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/